[versions]
agp = "8.5.1"
kotlin = "1.9.23"
tsBinding = "4.3.1"
lsp4j = "0.22.0"
androidxAnnotation = "1.8.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-collection = { module = "androidx.collection:collection", version = "1.4.2" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.2.1" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.6.1" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.4" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.8.0" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.8.4" }
material = { module = "com.google.android.material:material", version = "1.12.0" }
gms-instantapps = { module = "com.google.android.gms:play-services-instantapps", version = "18.1.0" }
tree-sitter-java = { module = "com.itsaky.androidide.treesitter:tree-sitter-java", version.ref = "tsBinding" }
tree-sitter = { module = "com.itsaky.androidide.treesitter:android-tree-sitter", version.ref = "tsBinding" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.13" }
junit = { module = "junit:junit", version = "4.13.2" }
gson = { module = "com.google.code.gson:gson", version = "2.11.0" }
jcodings = { module = "org.jruby.jcodings:jcodings", version = "1.0.58" }
joni = { module = "org.jruby.joni:joni", version = "2.2.1" }
snakeyaml-engine = { module = "org.snakeyaml:snakeyaml-engine", version = "2.7" }
jdt-annotation = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version = "2.3.0" }

tests-google-truth = { module = "com.google.truth:truth", version = "1.4.2" }
tests-robolectric = { module = "org.robolectric:robolectric", version = "4.11.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish.base", version = "0.28.0" }
