[versions]
agp = "8.0.2"
kotlin = "1.8.20"
lifecycle = "2.5.1"
tsBinding = "3.2.0"
lsp4j = "0.21.0"
androidxAnnotation = "1.6.0"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.10.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.3" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.7.2" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.6.1"}
material = { module = "com.google.android.material:material", version = "1.9.0"}
gms-instantapps = { module = "com.google.android.gms:play-services-instantapps", version = "18.0.1"}
tree-sitter-java = { module = "com.itsaky.androidide:tree-sitter-java", version.ref = "tsBinding" }
tree-sitter = { module = "com.itsaky.androidide:android-tree-sitter", version.ref = "tsBinding" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.12" }
junit = { module = "junit:junit", version = "4.13.2" }
gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
jcodings = { module = "org.jruby.jcodings:jcodings", version = "1.0.58" }
joni = { module = "org.jruby.joni:joni", version = "2.2.1" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "2.0" }
jdt-annotation = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version = "2.2.700" }
guava = { module = "com.google.guava:guava", version = "32.0.1-android" }

tests-google-truth = { module = "com.google.truth:truth", version = "1.1.3" }
tests-robolectric = { module = "org.robolectric:robolectric", version = "4.10.3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish.base", version = "0.25.3" }
